[workspace]
resolver = "3"
members = [
    "crates/wallrs-proto",
    "crates/wallrs-render",
    "crates/wallrs-audio",
    "crates/wallrs-content-image",
    "crates/wallrs-content-shader",
    "crates/wallrs-content-video",
    "crates/wallrs-core",
    "crates/wallrs-daemon",
    "crates/wallrs-cli",
]

[workspace.package]
version = "1.1.1"
edition = "2024"
license = "MIT OR Apache-2.0"
authors = ["Antonio S. Dromundo <sebastiandromundo@outlook.com>"]
repository = "https://github.com/asdrome/wallrs"
homepage = "https://github.com/asdrome/wallrs"
readme = "README.md"

[workspace.dependencies]
arc-swap = "1.7"
calloop = "0.14"
clap = { version = "4.5", features = ["derive"] }
pipewire = "0.10"
image = { version = "0.25", default-features = false, features = [
    "png",
    "jpeg",
    "webp",
] }
libmpv2 = "6.0"
libmpv2-sys = "4.0"
naga = { version = "30", features = ["glsl-in", "wgsl-out"] }
pollster = "0.3"
raw-window-handle = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"
smithay-client-toolkit = { version = "0.21.1", default-features = true, features = [
    "calloop",
    "system",
] }
thiserror = "2.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt"] }
wayland-client = { version = "0.31", default-features = true, features = [
    "system",
] }
wayland-protocols-wlr = { version = "0.3.12", features = ["client"] }
wgpu = "30"

[profile.release]
strip = "debuginfo"
