[package]
name = "wallrs-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "wallctl"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
image = { workspace = true }
naga = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
wallrs-content-shader = { path = "../wallrs-content-shader" }
wallrs-proto = { path = "../wallrs-proto" }
