[package]
name = "wallrs-audio"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
arc-swap = { workspace = true }
libmpv2 = { workspace = true }
pipewire = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
wallrs-proto = { path = "../wallrs-proto" }
