[package]
name = "wallrs-content-shader"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
naga = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
wallrs-audio = { path = "../wallrs-audio" }
wallrs-proto = { path = "../wallrs-proto" }
wallrs-render = { path = "../wallrs-render" }
wgpu = { workspace = true }
