[package]
name = "wallrs-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
calloop = { workspace = true }
pollster = { workspace = true }
raw-window-handle = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
smithay-client-toolkit = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
wallrs-audio = { path = "../wallrs-audio" }
wallrs-content-image = { path = "../wallrs-content-image" }
wallrs-content-shader = { path = "../wallrs-content-shader" }
wallrs-content-video = { path = "../wallrs-content-video" }
wallrs-proto = { path = "../wallrs-proto" }
wallrs-render = { path = "../wallrs-render" }
wayland-client = { workspace = true }
wgpu = { workspace = true }
